### ISSUE TITLE
unique_together check design on Cert model is flawed

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-x509#1]
In some cases it may happen that by using the app normally the unique_together check will fail.

We should avoid this, will try to collect more information on how to reproduce the issue.

**Comment by dimrozakis** [comment]
Any updates on this? Is this still an issue?

**Comment by nemesisdesign** [comment]
@dimrozakis I couldn't reproduce this issue anymore but I remember clearly one time it happened so I left the issue open just in case somebody else incurs in it.

Did you experience the same problem? If yes can you reproduce it?

**Comment by dimrozakis** [comment]
Hey @nemesisdesign 

>Did you experience the same problem? If yes can you reproduce it?

No, I haven't experienced the issue. I'm considering using this django app, and looked at the issue tracker to check for any known issues, and this seemed troubling, so I thought to ask.

**Comment by nemesisdesign** [comment]
@dimrozakis it hasn't happened anymore since that time and it only happened in my development environment. I might have caused some mess while developing. I will close this since I cannot reproduce it.
