### ISSUE TITLE
[UX] New vs import javascript switcher (hide/show different fields)

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-x509#10]
We need to improve the UX in the `Ca` and `Cert` admin, so that the difference between creating and importing CAs and Certs is clear without needing further explaination.

A `CharField` named `operation_type` (suggestions for better names are welcome) at the `ModelForm` level should be added, this field should use a select widget having 2 options:

1. (empty string, default)
2. new
3. import

## Case 1: empty

With the default option, all the fields except the name should be hidden.

## Case 2: new

When "new" is selected, all the hidden fields except `certificate` and `private_key` will be shown.

## Case 3: import

When "import" is selected, of all the hidden fields only the fields `certificate` and `private_key` will be shown.

**Comment by ferrine** [comment]
What can be the reason of not loaded js in Admin panel? I was following the guide to extend model
