### ISSUE TITLE
[CI] Move to Github actions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-x509#109]
Move to Github actions.

**Comment by codesankalp** [comment]
![image](https://user-images.githubusercontent.com/56037184/111430826-f4299080-8720-11eb-937f-f98539dd4b30.png)

The coverage fails to upload I don't know why :thinking:

**Comment by nemesisdesign** [comment]
@codesankalp maybe a temporary issue? Try again in a few hours and let me know.
