### ISSUE TITLE
[pki] CA can't be created when `Key length` set to `None` or `Digest algorithm` set to `None`

### ISSUE THREAD

**Issue by ManishShah120** [openwisp/django-x509#119]
### Steps to reproduce :-
**First Error**
1. Start creating a new CA.
2. Set the name.
3. Set the `Key length` choice to `None`.
4. Hit the save button.

Error[Screenshot]:-
![image](https://user-images.githubusercontent.com/45564404/116928944-57dd2e00-ac7b-11eb-8faf-29452079a560.png)

**Second Error**
3. Set the `Digest algorithm` to `None`
4. Hit the save button.

Error[Screenshot]:-
![image](https://user-images.githubusercontent.com/45564404/116929389-fb2e4300-ac7b-11eb-9c6a-894b43f754f2.png)

**Comment by nemesisdesign** [comment]
@pandafy @ManishShah120 @atb00ker issue moved to django-x509.
