### ISSUE TITLE
Serial number clash causes uncaught exception

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-x509#13]
Serial number may clash with an imported certificate.

We should add a way to catch this exception and generate a new serial number until an available serial number is found.

It's better to work on this issue after having solved #8.

**Comment by nemesisdesign** [comment]
@AZtheAsian @R9295 don't we have a GCI task for this as well?

**Comment by R9295** [comment]
Dunno how to go about it.

**Comment by nemesisdesign** [comment]
try this:

1. manually create a CA and from this CA generete a certificate, save its serial number, PEM private key and cert, save also the details of the CA
2. in a test, import the CA of step 1 and create a new cert signed by the same CA but set its serial number manually to the one you got in the previous step
3. now, in the same test, import the certificate and private key of step 1

This should trigger the issue, because you would be trying to import a cert which has a serial number and CA which already exist in the system (they have a `unique_together` constraint, see https://github.com/openwisp/django-x509/blob/master/django_x509/base/models.py#L468).
