### ISSUE TITLE
default_validity_start and default_ca_validity_end documentation is confusing 

### ISSUE THREAD

**Issue by ezaquarii** [openwisp/django-x509#29]
Creating Ca/Cert with timzone enabled results in Django warnings: "RuntimeWarning: DateTimeField Ca.validity_start received a naive datetime (2018-01-02 00:00:00) while time zone support is active.
  RuntimeWarning)" warning 
```

This looked like a bug, so I checked the implementation and I find the comment quite unhelpful.
def default_validity_start():
    """
    sets validity_start field to 1 day before the current date
    (avoids "certificate not valid yet" edge case)
    intentionally returns naive datetime (not timezone aware)
    """
   ...
```

Well, I see that we return naive date, that's what this 2-line function does. Re-using this code I'm wondering WHY we do this. My first reaction was "i'll fix it", but now I'm not sure what can of worms is hiding behind such change.

The hipster punctuation doesn't help understanding the intent too.

Please, please, please clarify the function documentation providing hints for end-users regarding this behavior.

**Comment by nemesisdesign** [comment]
The reason is that in some cases, because of timezone differences, when just created certificates were considered valid in a timezone (eg: Europe) but not yet valid in another timezone (eg: US).
So by default we set the start date of certificates so that it is valid from 00:00 AM on all timezones.
If you know a better way to implement this or disable this warning please let me know.

What do you mean for "hipster punctuation" BTW?

**Comment by ezaquarii** [comment]
Complete lack of it. :)

Anyway, thanks for explanation. Now I understand the implications. Would you have anything against if I create a PR with updated Docstring?

**Comment by nemesisdesign** [comment]
I would be totally in favour!
English lessons for free are always welcome :-)

**Comment by nemesisdesign** [comment]
@ezaquarii any news on this?

**Comment by ezaquarii** [comment]
Doh! I was busy and forgot about it. Don't close it yet, I'll update it this weekend.

**Comment by ezaquarii** [comment]
Opened PR.

**Comment by nemesisdesign** [comment]
We forgot to close this :-)
