### ISSUE TITLE
Static files are not loaded

### ISSUE THREAD

**Issue by ferrine** [openwisp/django-x509#37]
What can be the reason of not loaded js in Admin panel? I was following the guide to extend model

I got a workaround to solve the problem with staticfiles
```python
import os
import importlib
def pkg_static(pkg, static='static'):
    return os.path.join(os.path.dirname(importlib.util.find_spec(pkg).origin), static)

...


STATICFILES_DIRS = [pkg_static('django_x509')]
```

Is there any smarter way to do that?

**Comment by nemesisdesign** [comment]
Django can't load static files or override templates of apps which are not listed in `INSTALLED_APPS`.

We solved this problem within OpenWISP with a StaticFinder and a TemplateLoader (the same problem happens for templates too), more info here: https://github.com/openwisp/openwisp-utils#using-dependencyloader-and-dependencyfinder

I realize now this is not documented, if you could send a PR with an additional hint in the README (in the section which explains how to extend the app) it would be great.

**Comment by nemesisdesign** [comment]
I've updated the README to include instructions on how to solve this problem.
