### ISSUE TITLE
Add support for django 2.1

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-x509#39]
Add support for django 2.1.

**Comment by atb00ker** [comment]
I checked out the [Django 2.1 release docs](https://docs.djangoproject.com/en/2.1/releases/2.1/#backwards-incompatible-changes-in-2-1) and then upgraded the version to 2.1, did python runtest.py and manually checked all the buttons i could find, everything seems to work, no change needed.
@nemesisdesign , do i need to test it in any specific way / is any functionality expected to fail?
Or should i simply change `django>=2.0,<2.2` in the `requirements.txt`
