### ISSUE TITLE
Curious about subject alternative name support

### ISSUE THREAD

**Issue by unquietwiki** [openwisp/django-x509#4]
Google Chrome is apparently enforcing this extension; phasing it by version 65.

* https://support.google.com/chrome/a/answer/7391219?hl=en
* https://www.openssl.org/docs/man1.0.2/apps/x509v3_config.html#Subject-Alternative-Name

**Comment by nemesisdesign** [comment]
I was thinking if it wouldn't be better to refactor extensions to have their own db table with a relation to certificates, that way it would be easier to implement and mantain different extensions.

Regarding this specific issue, we can define a setting with mandatory extensions and default configurations.

**Comment by unquietwiki** [comment]
@nemesisdesign Thank you for responding so quickly on this 👍 I found this project while looking for an easy way to create internal certificates, and then ran into that Google error while trying them out. Figure that's going to be more of an issue over the next year, regardless who's using them.

**Comment by nemesisdesign** [comment]
@unquietwiki, are you using this app to generate SSL certificates for browsers?
We are using it in @openwisp to generate VPN certificate so our requirements are a bit different.
It would be nice to make this app usable for different use cases.

**Comment by unquietwiki** [comment]
@nemesisdesign (nods) I was trying to find something to make it easier for my bosses to manage OpenSSH certs. The idea seems to work, other than that subject alternate thing.

**Comment by nemesisdesign** [comment]
PS: when figuring out the right values to put, try a google search, for example [this stackoverflow Q&A may contain an useful tip](https://stackoverflow.com/questions/24475768/is-it-possible-to-set-subjectaltname-using-pyopenssl).

**Comment by unquietwiki** [comment]
@nemesisdesign I did a fork + pushed an update with 3 files I modified. It basically does an ad-hoc conversion of the commonName to a subjectAltName for client certificates. In doing some troubleshooting, I also removed weaker/deprecated key sizes and SHA-1 from the choice lists.

https://github.com/openwisp/django-x509/compare/master...unquietwiki:master

**Comment by unquietwiki** [comment]
(ponders) Earlier, before making that modification, I was pondering being able to add the SAN as a separate field. If that's doable at all (the code I modified shows some separation between fields and processing, so I'm not sure how cleanly that propagates); some of the use cases and examples I'm finding involve generating a CSR in place of accepting a cert+key set. Maybe if a CN field can be added, a CSR field can be added as well?

**Comment by nemesisdesign** [comment]
Adding a field for each possible extension is not a viable option, I'm much more inclined to go the admin inline path.

Regarding how to implement CSR, I have no idea. Some inspiration may be looked for in this unmantained full featured pki django app: https://github.com/dkerwin/django-pki
