### ISSUE TITLE
OperationalError: no such column: django_x509_ca.organization

### ISSUE THREAD

**Issue by Gobiviswa** [openwisp/django-x509#54]
Hi ,

it was working well for long time. Suddenly "OperationalError: no such column: django_x509_ca.organization " error came. not able to use Ca and Cert tables. Even in django admin page also it shows same error. please help me in this.
Thanks.

**Comment by nemesisdesign** [comment]
Have you run the migrations?
`./manage.py migrate`

**Comment by nemesisdesign** [comment]
Closing because can't replicate this issue.
