### ISSUE TITLE
Outdated cryptography 2.3.1

### ISSUE THREAD

**Issue by ezaquarii** [openwisp/django-x509#55]
Hi,

Cryptography package has been bumped to 2.6.x, but pypi release of x509 still depends on <2.4.0. Is there any intention to update it?

I see that on master it is upgraded to >=2.4, <2.5, but that version is not in pypi.

**Comment by nemesisdesign** [comment]
sure let's fix that, send a patch when you can. I'd do it myself but there are so many pull requests on different OpenWISP modules that I need to review before I can do this

**Comment by ezaquarii** [comment]
PR opened.

**Comment by nemesisdesign** [comment]
#57 Fixed this, thank you @ezaquarii
