### ISSUE TITLE
[django] Add support for django 2.2

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-x509#58]
Add support for django 2.2

**Comment by beaylott** [comment]
#61

**Comment by atb00ker** [comment]
Complete! :smile:

**Comment by L3viathan** [comment]
While this is complete, the last release on PyPI is from September 5, 2018. Could you push a release to PyPI so we can update without having to build the package ourselves?

**Comment by atb00ker** [comment]
Django 3.0 is going to be released in less than a month, I suppose we can go to it directly from the current version! :smile:

**Comment by nemesisdesign** [comment]
@L3viathan the 0.5.0 release is out
