### ISSUE TITLE
[requirements] Update dependencies

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-x509#65]
We need to update all the dependencies including update to django 3.0

**Comment by IAmAMissingColon** [comment]
Drop support of python2 ?

**Comment by okraits** [comment]
As this is a reusable app, we shouldn't drop support of Python 2 now.

**Comment by IAmAMissingColon** [comment]
Oh, Got It Now ! Thank You :smiley:

**Comment by nemesisdesign** [comment]
The last release of django-x509 which supports python 2 will be 0.5.0, which I released a few days ago: https://github.com/openwisp/django-x509/releases/tag/0.5.0

We can prepare the next release to be python 3 only in order to support the newer versions of django.

**Comment by nemesisdesign** [comment]
PS: let's leave this for the Google Code-In.

**Comment by IAmAMissingColon** [comment]
Hello can I work on it ?

**Comment by atb00ker** [comment]
It's not in GCI system for now! :smile:

**Comment by IAmAMissingColon** [comment]
Python3.5 doesn't support Django3 right ? So, I have to exclude it ?

**Comment by IAmAMissingColon** [comment]
And the requires.io shows all dependencies are up-to-date except Django

**Comment by IAmAMissingColon** [comment]
Here's Kind of summary

* Some modules like six, @python_2_unicode_compatible has been removed in django3 or only supported for it's older vesrions (Older versions of Django)

* Python3.5 Dosen't support Django3.0 as I mentioned in my previous comment. Please tell me If I'm not right ! I will research more on it :smile: 

* All dependenices are up-to-date Requires.io[https://requires.io/github/openwisp/django-x509/requirements/?branch=master](url)

Is anything left please tell me :smile:

**Comment by atb00ker** [comment]
@IAmAMissingColon 

- For six, there are 2 possible solutions mentioned [here](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis), if it's a library and you need alternatives for that library, please comment the name of the library here as well so that we can look for an alternative library.

- No, we are not dropping support for all other versions of Django, only adding support.

- That's great! :smile:

**Comment by atb00ker** [comment]
Regarding `jsonfield`, I just read : https://github.com/dmkoch/django-jsonfield/
Which makes this task a hard one I suppose! :smile:

@nemesisdesign What do you think? :smile:

**Comment by nemesisdesign** [comment]
For Python, we should test python 3.6 and 3.7.

**Comment by nemesisdesign** [comment]
For the jsonfield we can use this one: https://github.com/rpkilby/jsonfield2
Looks like a fork of the one we're using, with the difference that is actually maintained.

**Comment by Weirdo914** [comment]
I have taken this up so do I have remove support for python 2?

**Comment by nemesisdesign** [comment]
@Weirdo914 no, we'll do that in a separate issue

**Comment by nemesisdesign** [comment]
let's support only django 2.2.x and django 3.0.x, on python 3.6 and 3.7.

The last python 2.7 compatible release with support for old django versions is 0.5.0.
