### ISSUE TITLE
[bug] Fix JavaScript error on django 2.2

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-x509#74]
I see an error on javascript in the latest release with django 2.2.

Go to the CA or Certs form to see the error.

Note: Ensure django 2.2 is installed in your virtualenv, clear the cache (actually in google chrome or chromium you can go to the network tab in the developer console and check "disable cache" and repeat the process.

You should see a JS error.

**Comment by marfgold1** [comment]
It seems like `x509-admin.js` is called first then `jquery.init.js` called later. That's why `django.jQuery` is still not defined.

![Screenshot from 2019-12-21 21-49-46](https://user-images.githubusercontent.com/34912365/71309572-08a6ac80-243c-11ea-8ae0-ec55e7de6804.png)

**Comment by atb00ker** [comment]
@marfgold1 read django 2.2 release notes, that contains the answer to fix this! :smile:

**Comment by marfgold1** [comment]
Ahh okay I see how to solved the problem now.
I can do it, but I leave it to other since I'm still on another task 😅

**Comment by nikitaermishin** [comment]
@marfgold1 appreciate your previous work, I will end it :grinning:
