### ISSUE TITLE
Maximum length of x509 serial number is incorrect

### ISSUE THREAD

**Issue by Weirdo914** [openwisp/django-x509#78]
The current maximum length of serial number in x509 model is 39. The maximum value of x509 serial number is `2^159` which is equal to `730750818665451459101842416358141509827966271488` and has a length of 48.
So while importing existing ca, I got this validation error- `Ensure this value has at most 39 characters (it has 48).`

**Comment by nemesisdesign** [comment]
Thanks for reporting, this bug report is correct and we should act upon.

**Comment by marfgold1** [comment]
I can write a test unit too for this issue, if you want @nemesisdesign :smile:
