### ISSUE TITLE
[pki] Add possibility of renewing certificates

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-x509#83]
We should add a way to renew expired certificates, a model method and an admin action.

It should also be possible to renew a CA, which in turn should renew all the certificates related to it.

Renewing would mean generate a new x509 certificate and private key which replaces the old ones.

**Comment by NoumbissiValere** [comment]
Let me look at this :smile:

**Comment by NoumbissiValere** [comment]
@nemesisdesign when renewing a CA, should only the certificates which have expired been renewed or all certificates linked to that CA should be renewed

**Comment by nemesisdesign** [comment]
All certificates.
